[package]
name = "libpal"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
aes= "0.8.3"
generic-array = "0.14.7"
